- name: Ivan Ogasawara
  email: ivan.ogasawara@gmail.com
  num_commits: 1
  first_commit: 2019-09-05 09:49:33
- name: Hameer Abbasi
  email: hameerabbasi@yahoo.com
  alternate_emails:
  - einstein.edison@gmail.com
  - habbasi@Hameers-MacBook-Pro.local
  num_commits: 36
  first_commit: 2019-06-21 06:41:38
- name: Anthony Scopatz
  email: scopatz@gmail.com
  num_commits: 18
  first_commit: 2019-05-10 16:21:01
