jobs:
- job: Linux
  variables:
    python_version: '3.5'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - template: ci/azure-steps.yml
  strategy:
    matrix:
        Python37:
          python_version: '3.7'
        Python36:
          python_version: '3.6'
        Python35:
          python_version: '3.5'
- job: MacOS
  variables:
    python_version: '3.5'
  pool:
    vmImage: 'macos-10.13'
  steps:
    - template: ci/azure-steps.yml
- job: Windows
  variables:
    python_version: '3.5'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
    - template: ci/azure-steps.yml
