jobs:
- job: Linux
  variables:
    python_version: '3.5'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - template: ci/azure-steps.yml
  strategy:
    matrix:
        Python37:
          python_version: '3.7'
        Python36:
          python_version: '3.6'
        Python35:
          python_version: '3.5'
