version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo apt-get update && sudo apt-get install hdf5
            python3 -m venv venv
            . venv/bin/activate
            pip install https://github.com/Quansight/h5py/archive/datetime64.zip
            pip install pytest
            pip install -e .

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest
