version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Download HDF5
          command: |
            wget https://github.com/Quansight/h5py/archive/datetime64.zip


      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pyproject.toml" }}-{{ checksum "datetime64.zip" }}

      - run:
          name: install dependencies
          command: |
            sudo apt-get update && sudo apt-get install libhdf5-10* libhdf5-dev
            python3 -m venv venv
            . venv/bin/activate
            pip install ./datetime64.zip numba
            pip install pytest
            pip install -e .

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "pyproject.toml" }}-{{ checksum "datetime64.zip" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest
