version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest

    working_directory: ~/repo

    steps:
      - checkout


      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "pyproject.toml" }}

      - run:
          name: install dependencies
          command: |
            sudo apt-get update && sudo apt-get install libhdf5-10* libhdf5-dev
            python3 -m venv venv
            . venv/bin/activate
            pip install -e .[tests]

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "pyproject.toml" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest --pyargs bth5
